name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Angular App
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist/stock-app"
          output_location: ""  # 空にすることでビルドをスキップ
